// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME")
                        .HasDefaultValue(new DateTime(2022, 7, 12, 22, 55, 25, 695, DateTimeKind.Local).AddTicks(9848))
                        .HasColumnName("CreationDate");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("DATE")
                        .HasColumnName("ExpirationDate");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("ProductCode")
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("ProductCode");

                    b.Property<string>("ProductName")
                        .HasColumnType("VARCHAR(150)")
                        .HasColumnName("ProductName");

                    b.HasKey("Id")
                        .HasName("Pk_productid");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("Domain.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("VARCHAR(MAX)")
                        .HasColumnName("Email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Password")
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("Password");

                    b.Property<string>("UserName")
                        .HasColumnType("VARCHAR(25)")
                        .HasColumnName("UserName");

                    b.HasKey("Id")
                        .HasName("Pk_userid");

                    b.ToTable("User");
                });
#pragma warning restore 612, 618
        }
    }
}
